#!/usr/bin/env python3
"""Regenerate the golden md5 hashes for the synthetic test fixtures.

Run this **after** an intentional, reviewed change to the filter's output —
never as a workaround for a failing test. The script feeds every fixture
through `core.zit.IT` and dumps one line per (fixture, params, frame) into
`tests/integration/fixtures/golden_hashes.txt`.

Reference comparison against the upstream C++ build is currently deferred
(upstream is API3 and segfaults under VS R76's compat shim; see
`docs/upstream_reference.md`). Until that's set up, these hashes act as
regression guards: they pin the Zig port's current behaviour, so any
unintended drift will surface in CI.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import vapoursynth as vs                     # noqa: E402
import gen_testclip                          # noqa: E402

PLUGIN_PATH = ROOT / "zig-out" / "lib" / "libzit.so"
GOLDEN_PATH = ROOT / "tests" / "integration" / "fixtures" / "golden_hashes.txt"


def frame_md5(clip: vs.VideoNode, n: int) -> str:
    f = clip.get_frame(n)
    h = hashlib.md5()
    for p in range(f.format.num_planes):
        h.update(bytes(f[p]))
    return h.hexdigest()


# (fixture_name, fps, threshold, pthreshold) — params we pin in golden hashes.
PARAM_GRID = [
    ("constant_color",     30, 20, 75),
    ("constant_color",     24, 20, 75),
    ("constant_large",     24, 20, 75),
    ("constant_mod16",     24, 20, 75),
    ("two_frame_telecine", 30, 20, 75),
    ("two_frame_telecine", 24, 20, 75),
    ("interlaced_stripes", 30, 20, 75),
    ("interlaced_stripes", 24, 20, 75),
    ("two_frame_telecine", 24, 10, 50),  # threshold sensitivity
    ("two_frame_telecine", 24, 40, 150),
]


def main() -> int:
    if not PLUGIN_PATH.exists():
        print(f"plugin not found: {PLUGIN_PATH}\nrun `zig build` first", file=sys.stderr)
        return 1

    core = vs.core
    core.std.LoadPlugin(str(PLUGIN_PATH))

    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = ["# Auto-generated by scripts/regen_golden.py — do not hand-edit.\n",
                       "# fields: fixture | fps | threshold | pthreshold | frame_idx | md5\n"]
    for fixture, fps, th, pth in PARAM_GRID:
        clip = gen_testclip.FIXTURES[fixture]()
        out = core.zit.IT(clip, fps=fps, threshold=th, pthreshold=pth)
        print(f"  {fixture:<22} fps={fps} th={th} pth={pth} -> {out.num_frames} frames", flush=True)
        for n in range(out.num_frames):
            digest = frame_md5(out, n)
            lines.append(f"{fixture}|{fps}|{th}|{pth}|{n:04d}|{digest}\n")

    GOLDEN_PATH.write_text("".join(lines))
    print(f"wrote {len(lines) - 2} hash lines to {GOLDEN_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
